### ISSUE TITLE
Coverage?

### ISSUE THREAD

**Issue by EitanGrossman** [bdproto/bdproto#18]
I think it would be good to have a summary of the coverage per area, so we can know what areas we should target in searches, rather than focusing on particular areas.

**Comment by bambooforest** [comment]
I had another look at this and it's not a simple request because language family level codes, e.g. grea1284 (Greater Central Philippine), in BDPROTO are not associated with macroarea, lat, long, etc., figures in Glottolog, since those are reserved to language/dialect level codes.

I produce some numbers here (towards the bottom, currently):

https://github.com/bdproto/bdproto/blob/master/src/descriptive_stats.md

But these numbers are completely off and represent essentially language isolates (which are their own family).

TODO: infer the macroarea of a language family in Glottolog by it's daughter language(s)

**Comment by bambooforest** [comment]
The descriptive stats URL above handles this -- but first we need to finish #19
